apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: yys172/jmeter-with-influxdb2-slave:5.6.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: jmeter-jmx
              mountPath: /jmeter_jmx
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
            requests:
              memory: 800Mi
              cpu: 100m
          env:
            - name: TZ
              value: "Asia/Shanghai" # 你想要的时区
          ports:
            - containerPort: 1099
            - containerPort: 50000
      volumes:
        - name: jmeter-jmx
          persistentVolumeClaim:
            claimName: pvc-jmeter-jmx
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_mode: slave
