apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx-jmeter
data:
  jmeter_report.conf: |
    server {
      listen 8012;
      server_name localhost;

      location ~ ^/jmeter_report/(?<subdirectory>.*) {
          alias /jmeter_report/$subdirectory;
          index index.html;
        }
    }
