apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jmeter-jmx
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /jmeter_jmx
    server: 10.111.7.73
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jmeter-jmx
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
