name: Build Docker Images

on:
  push:
    tags:
      - v*

env:
  REGISTRY: yys172
  BASE_IMAGE_NAME: jmeter-with-influxdb2
  MASTER_IMAGE_NAME: jmeter-with-influxdb2-master
  SLAVE_IMAGE_NAME: jmeter-with-influxdb2-slave

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB }}

      - name: Extract metadata for base image
        id: base_meta
        uses: docker/metadata-action@v5
        with:
          # images: my-docker-hub-namespace/my-docker-hub-repository
          images: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}

      - name: Build and push base image
        id: push_base
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.base_meta.outputs.tags }}
          labels: ${{ steps.base_meta.outputs.labels }}

      - name: Extract metadata for master image
        id: master_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.MASTER_IMAGE_NAME }}

      - name: Build and push master image
        id: push_master
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile-master
          platforms: linux/amd64
          tags: ${{ steps.master_meta.outputs.tags }}
          labels: ${{ steps.master_meta.outputs.labels }}

      - name: Extract metadata for slave image
        id: slave_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.SLAVE_IMAGE_NAME }}

      - name: Build and push slave image
        id: push_slave
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile-slave
          platforms: linux/amd64
          tags: ${{ steps.slave_meta.outputs.tags }}
          labels: ${{ steps.slave_meta.outputs.labels }}
